on: [push]

name: build

jobs:
  build_sonar_scanner:
    name: Build sonar-scanner
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      
    steps:
    - uses: actions/checkout@v4

    - name: Build sonar-scanner Docker Images
      uses: philips-software/docker-ci-scripts@d0045b844f08b0dcb4c62bd4acf6c36877404dae # v5.1.0
      with:
        dockerfile: 4 
        image-name: sonar-scanner
        tags: latest 4 4.7 4.7.0 4.7.0.2747
        slsa-provenance: true
        sign: true
        sbom: true
      env:
        REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        REGISTRY_TOKEN: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
        KEYLESS: true
