on: [push]

name: build

jobs:
  build_sonar_scanner:
    name: Build sonar-scanner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build sonar-scanner Docker Images
      uses: philips-software/docker-ci-scripts@v4.1.3
      with:
        dockerfile: 4 
        image-name: sonar-scanner
        tags: latest 4 4.6 4.6.2 4.6.2.2472
        slsa-provenance: true
        sign: true
        sbom: true
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
        COSIGN_PRIVATE_KEY: '${{ secrets.COSIGN_PRIVATE_KEY }}'
        COSIGN_PASSWORD: '${{ secrets.COSIGN_PASSWORD }}'
        COSIGN_PUBLIC_KEY: '${{ secrets.COSIGN_PUBLIC_KEY }}'
