on: [push]

name: build

jobs:
  build_sonar_scanner:
    name: Build sonar-scanner
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      
    steps:
    - uses: actions/checkout@v3

    - name: Build sonar-scanner Docker Images
      uses: philips-software/docker-ci-scripts@69ca3b3e358f8746c67341d6ab551ef5ec25a36c # v5.0.0
      with:
        dockerfile: 4 
        image-name: sonar-scanner
        tags: latest 4 4.7 4.7.0 4.7.0.2747
        slsa-provenance: true
        sign: true
        sbom: true
      env:
        REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        REGISTRY_TOKEN: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
        KEYLESS: true
